RRZE-HPC/likwid

src/configuration.c

Let's tell the user that he might have to adjust the PATH environment variable...

Make error message a bit more verbose

---

groups/sandybridgeEP/L3CACHE.txt

Updated L3CACHE.txt

---

config.mk

remove erroneous dollar sign

---

src/affinity.c
src/configuration.c
src/cpustring.c
src/includes/likwid.h
src/includes/numa.h
src/includes/numa_proc.h
src/includes/perfgroup.h
src/includes/power.h
src/includes/timer.h
src/memsweep.c
src/numa.c
src/numa_proc.c
src/perfgroup.c
src/perfmon.c
src/timer.c

API: Declare parameters const where applicable

---

groups/broadwell/L3.txt

Fix category on Broadwell.

---

groups/knl/ENERGY.txt

Use PWR3 to compute DRAM energy and power metrics.

Update ENERGY.txt for knl

---

doc/lua-doxygen.md
src/applications/likwid-features.lua
src/applications/likwid-mpirun.lua
src/applications/likwid-perfctr.lua
src/applications/likwid-powermeter.lua
src/applications/likwid-topology.lua

Fix typos in Lua files

---

bench/armv8/daxpy.ptt
bench/armv8/triad.ptt

added triad and daxpy bench kernels on armv8

---

src/includes/likwid.h

Corrected markerNextGroup comment: previously said it should be called
in a parallel region, corrected to say serial region.
Added hints on barriers when calling these functions in parallel regions
Resolves #292

Improved doxygen comments

---

examples/C-likwidAPI.c

I have added the concept of multiple 'work items' (e.g. multiple loops), and showcase perfmon_getLastResult() to print counts for each work item. Should match better with typical use cases.
I also removed use of strtok() - as it modified 'estr', it could only be used once. Replaced with a simple array.

Add more structure to C-likwidAPI.c, to better match use cases

---

src/topology_gpu.c

to differ from the ones used in nvmon* . See [likwid-users mailing list post](https://groups.google.com/g/likwid-users/c/HEwUqzjHJAQ).

Rename the function pointers in topology_gpu.c 

---

src/includes/libperfctr_types.h
src/includes/perfmon_types.h
src/libperfctr.c

Update for the MarkerAPI for less overhead, especially for multi-socket runs

Update cpu marker api

---

src/access-daemon/accessDaemon.c
src/includes/topology.h
src/perfmon.c
src/power.c
src/topology.c

Add support for AMD Zen2 (family 0x17, model 0x60)

---

src/affinity.c

Example for the bug:
```
$ likwid-pin -c S1:0 -q likwid-pin -p
Domain 0:
Tag N: 12
Domain 1:
Tag S0: 12
Domain 2:
Tag C0:
Domain 3:
Tag C1:
Domain 4:
Tag M0:
```

Fix for affinity in reduced cpusets

---

src/luawid.c

Don't set cpuset in unpinned case

---

test/Makefile
test/triad.cu

Starts an OpenMP thread for every GPU that is present and makes a separate benchmark for each GPU.

Add multi GPU capability to test/triad.cu

---

src/access_x86_pci.c

Fallback to procfs based PCI detection if hwloc based detection fails.

---

src/includes/likwid.h
src/includes/nvmon_perfworks.h
test/gitlab-ci/generate_arch_jobs.sh

Fixes segfault reported by @carstenbauer in https://github.com/JuliaPerf/LIKWID.jl/issues/34

Nvmon: store pointers to events internally

---

groups/CLX/ENERGY.txt
groups/ICX/ENERGY.txt
groups/broadwellD/ENERGY.txt
groups/broadwellEP/ENERGY.txt
groups/haswellEP/ENERGY.txt
groups/skylakeX/ENERGY.txt

Add Uncore clock to server-class architectures

---

src/includes/perfmon_perfevent.h
src/includes/perfmon_zen.h

Change lock for DataFabric counters for Zen family (0x17) to die

---

src/includes/likwid.h
src/meta.c

Adds the following functions:
- `likwid_getMajorVersion()`
- `likwid_getMinorVersion()`
- `likwid_getBugfixVersion()`
- `likwid_getNvidiaSupport()`
- `likwid_getMaxSupportedThreads()`
- `likwid_getMaxSupportedSockets()`
See #428 and #430

Add functions to return support status and version of the library

---

src/applications/likwid-mpirun.lua

Check SLURM commands when mpitype == slurm

---

src/applications/likwid-mpirun.lua

Fixes slurm statements

---

Makefile
src/topology_hwloc.c

Fix A64FX FX1000 topology detection

---

src/includes/likwid.h

This PR adds more thorough documenation for the API features provided with the Rocmon Marker API. All contents are based on the existing NVIDIA docs.

update documentation for rocmon api

---

src/perfgroup.c
src/perfmon.c

Fix for Intel Tigerlake

---

groups/arm64fx/ENERGY.txt
src/includes/perfmon_perfevent.h

adding energy measurement support for a64fx and unify the internal counter scaling

---

src/includes/likwid.h
src/includes/perfmon_broadwell.h
src/includes/perfmon_goldmont.h
src/includes/perfmon_haswell.h
src/includes/perfmon_icelake.h
src/includes/perfmon_ivybridge.h
src/includes/perfmon_knl.h
src/includes/perfmon_sandybridge.h
src/includes/perfmon_sapphirerapids.h
src/includes/perfmon_silvermont.h
src/includes/perfmon_skylake.h
src/includes/perfmon_tigerlake.h
src/includes/perfmon_zen.h
src/includes/perfmon_zen2.h
src/includes/perfmon_zen3.h
src/includes/perfmon_zen4.h
src/includes/perfmon_zen4c.h
src/includes/power.h

Update PowerData to 64 bit types. Fixes #622

---

src/timer.c

Fix RDTSC measurements for accuracy:
