RRZE-HPC/likwid

src/topology_hwloc.c

Hwloc only annotate the inclusiveness of the cache detected by his x86 backend. It can't detect cache without binding to his PU. 
If at a level the cache detected as 0 by the linux backend has no bindable pu his inclusiveness will be null.
As likwid assume that all the cache at one level are the same, cousin inclusiveness can be used instead.
May fix https://groups.google.com/forum/#!topic/likwid-users/XD6W1z203wE
(unless additional information are provided and cgroup weren't used)

 topology_hwloc : debug cache inclusiveness detection with some core/PU restricted by cgroups

---

src/applications/likwid-powermeter.lua

Simple fix, just pass the correct domain, not zero.

Fix for likwid-powermeter, which uses the wrong RAPL domain when requesting energy

---

groups/broadwellD/CACHES.txt
groups/broadwellEP/CACHES.txt
groups/haswell/CACHES.txt
groups/haswellEP/CACHES.txt
groups/ivybridgeEP/CACHES.txt
groups/sandybridgeEP/CACHES.txt

Fix for L2 to L3 evict volume metric in all CACHES.txt

---

config.mk

For LIBLIKWIDPIN the wrong INSTALLED_PREFIX instead of the correct INSTALLED_LIBPREFIX is used to determine the path to the shared object. Fixed this in config.mk.

set correct path to liblikwidpin

---

src/includes/perfmon_skylake.h

While the frontend events were defined, the MSR_PEBS_FRONTEND register apparently wasn't configured anywhere.

Implement Skylake frontend events

---

src/applications/likwid-mpirun.lua

The environment variables MPI_LOCALNRANKS and MPI_LOCALRANKID don't appear to be native to SLURM. So as to not break sites alread using likwid that may have these MPI_LOCAL* vars use the SLURM_* equivalents only if the MPI_LOCAL* vars are unavailable.

Use SLURM_* vars when no MPI_LOCAL* vars

---

src/includes/perfmon_perfevent.h

Some return statements are missing when using the perf_event support.
To be compliant with the other headers, I added the same statements where they were missing.

Add missing return statements for the perf_event support.

---

src/includes/perfmon_perfevent.h
src/includes/perfmon_types.h
src/perfmon.c

Add the possibility to use the PID and flags parameters for the perf_event_open call when using the perf_event interface (#96).

Add the support of the pid and flags parameters (perf_event).

---

src/includes/perfmon_zen.h

Is there any reason why these are inverted? If I'm trying to filter events by thread, I usually think of "I'd like to get events from *these* threads", not "I'd like to **not** get events from these threads".

AMD Zen: Don't invert thread/slice selectors

---

src/calculator.c

I'm a member of the Pinguem.ru competition on finding errors in open source projects. Error, found using PVS-Studio:
likwid/src/calculator.c     771     err     V586 The 'free' function is called twice for deallocation of the same memory space. Inspect the first argument. Check lines: 760, 771.

Fixed double `free`

---

src/access_x86_msr.c

Got an buffer overflow since /dev/cpu/18/msr_safe did not fit within the 20 chars

Increased MAX_LENGTH_MSR_DEV_NAME

---

src/applications/likwid-mpirun.lua

- to check for the first core in a socket, a comparison of the cpu id is
done; unfortunately, the comparison is between a string and integers
- converting the cpu id to a number fixes the comparison and the uncore
counters (e.g., memory related counters) are read by the first cores
in each socket

fix missing uncore measurements with likwid-mpirun

---

Makefile

The cmake config file should point to the directories where likwid is
installed, not where it was built.

change PREFIX to INSTALLED_PREFIX for cmake config

---

src/applications/likwid-mpirun.lua

- the problem lies in setting SLURM_NODELIST in likwid-mpirun
- currently, the hostlist is read from a scontrol command using a lua
pipe with f:read('*a')
- this leads to line break at the end of the environment variable
SLURM_NODELIST, causing srun to segfault
- this can be fixed by using f:read('*l') because the scontrol output
should always be only one line -> the line break is ignored

fix likwid-mpirun bug with slurm

---

src/applications/likwid-mpirun.lua

`measurments` -> `measurements`

Fix typo in likwid-mpirun

---

bench/src/bench.c

Changing type from 'int' to 'size_t' to avoid overflowing.
At some cases, offset may be bigger than 2 147 483 647, that cause negative number and access to wrong memory address. 
example:
likwid-bench -t copy_avx -w S0:48GB:48 −i 2048

Changing type of variable 'offset'

---

test/check_events_files.py

Please consider this PR which introduces checks for event names uniqueness.
Running the updated script as 
`<path_to_likwid>/test/check_events_files.py events -v
`
produces ~90 cases when the same name is used for events with different UMASK.

Add check for event name duplicates

---

test/check_events_files.py

Prompt the user to use --input-dir option if no files found in the default input directory.

Warn user if there is no any events files found in default directory.

---

bench/includes/allocator.h
bench/includes/strUtil.h
bench/includes/test_types.h
bench/likwid-bench.c
bench/src/allocator.c
bench/src/bench.c
bench/src/strUtil.c
doc/likwid-bench.1

with a new command line option and update documentation.
The first-touch mode can be activated with -W instead of -w for a group. Stream placement is not available in first-touch mode.
This PR is similar to #212 but enables both modes and introduces a command line option. In #212 the first-touch mode is made the default.

Add initialization per thread 

---

bench/includes/threads.h
bench/likwid-bench.c
bench/src/threads.c

Up to now, different work groups must have the same thread number for likwid-bench to work properly. With this change, different work groups can have different numbers of threads, which is useful for e.g., when one wants to have 2 threads on the first socket and only one on the second.
Example: `likwid-bench -t copy -w S0:10MB:2 -w S1:10MB:1`

Allow arbitrary thread numbers per work group in likwid-bench

---

bench/includes/bstrlib_helper.h
bench/includes/isa_armv7.h
bench/includes/isa_armv8.h
bench/includes/isa_x86-64.h
bench/includes/isa_x86.h
bench/includes/ptt2asm.h
bench/includes/test_types.h
bench/likwid-bench.c
bench/src/bstrlib_helper.c
bench/src/ptt2asm.c
doc/likwid-bench.1
src/bstrlib_helper.c
src/includes/bstrlib_helper.h

This PR allows the addition of benchmark kernels to likwid-bench without recompilation. likwid-bench searches in $HOME/.likwid/bench/<arch> for PTT files, converts them the arch-specific assembly and compiles the file.

Likwid bench/dynload

---

src/includes/perfmon_types.h
src/perfmon.c

Issue #57 
This adds an event GENERIC_EVENT that can be used with all counters like:
GENERIC_EVENT:<counter>:CONFIG=0x00:UMASK=0x00 (:other options available for the counter)

Add support for generic event

---

src/includes/likwid.h

```c++
#ifndef LIKWID_MARKER_INIT
#include <likwid-markers.h>
#endif
```
```c++
#ifndef LIKWID_MARKER_INIT
#include <likwid-marker.h>
#endif
```

Fixed likwid-markers.h -> likwid-marker.h in likwid.h

---

bench/x86-64/peakflops.ptt
bench/x86-64/peakflops_avx.ptt
bench/x86-64/peakflops_avx512.ptt
bench/x86-64/peakflops_avx512_fma.ptt
bench/x86-64/peakflops_avx_fma.ptt
bench/x86-64/peakflops_sp.ptt
bench/x86-64/peakflops_sp_avx.ptt
bench/x86-64/peakflops_sp_avx512.ptt
bench/x86-64/peakflops_sp_avx512_fma.ptt
bench/x86-64/peakflops_sp_avx_fma.ptt
bench/x86-64/peakflops_sp_sse.ptt
bench/x86-64/peakflops_sse.ptt

* add different variants AVX/AVX-512 with/without FMAs, similar to the other benchmarks
* higher unrolling of AVX/SSE variants to obtain better results (on Haswell)
* add missing description and annotation (number of instructions etc)

likwid-bench: improve peakflops micro benchmark

---

examples/C-internalMarkerAPI.c
examples/C-markerAPI.c
examples/Makefile

`C-markerAPI` is a simple example and `C-internalMarkerAPI` is more complete. Examples now work with current version of likwid (v5.0.1) and comments have been dramatically improved.
Mentioned in RRZE-HPC/likwid#292
Part of RRZE-HPC/likwid#297

#297 improve examples

---

src/includes/numa.h
src/includes/numa_virtual.h
src/numa.c
src/numa_hwloc.c
src/numa_proc.c
src/numa_virtual.c

This modifies the error handling to use a "virtual" NUMA node in case no proper one was found, in order to guarantee that there is always at least one, even on systems without any NUMA support (like on the Raspberry Pi 4).
Previously the hwloc backend already handled this on its own, so I extracted that code into a virtual "backend", which is used by both the proc and empty backends as well, in case no better info can be detected.
For memory usage the procfs is used, which was done by the hwloc backend as well, and for the  `numberOfProcessors` the `cpuid_topology.numHWThreads`  value is taken.
In order to avoid any behaviour changes the hwloc backend recomputes the `numberOfProcessors` on its own, not sure if that is a good or bad idea.
I have not gotten around to testing this on any …

Create virtual numa node in case detection fails

---

src/access-daemon/accessDaemon.c
src/includes/perfmon_types.h
src/includes/perfmon_zen3.h
src/includes/perfmon_zen3_counters.h
src/includes/perfmon_zen3_events.txt
src/includes/topology.h
src/perfmon.c
src/power.c
src/topology.c

Counter logic included for:
- Fixed-purpose counters
- General-purpose counters
- RAPL counters
- L3 counters
- Data fabric counters
Event list is currently empty but updated as soon as it is public

Add support for AMD Zen3 (Ryzen and probably Milan). 

---

src/includes/likwid.h

There is a small typo in bench/includes/likwid.h, src/includes/likwid.h.
Should read `access` rather than `sccess`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, sccess -> access

---

src/applications/likwid-setFrequencies.lua
src/applications/likwid.lua
src/frequency_cpu.c
src/includes/likwid.h
src/luawid.c

Add a reliable way to get the base frequency from register for Intel and AMD CPUs. This should reduce warnings printed by `likwid-setFrequencies`.

Reliable base freq

---

src/applications/likwid-perfctr.lua
src/applications/likwid-pin.lua
src/applications/likwid-powermeter.lua

This PR adds the export of the used HW threads through the environment variable `LIKWID_HWTHREADS` so that applications can use this knowledge. There is already an environment variable `LIKWID_THREADS` but it only exported by `likwid-perfctr` in MarkerAPI mode. In some cases, you need the knowledge also in non-instrumented applications.

Export list of hwthreads to wrapped application

---

src/access-daemon/accessDaemon.c
src/cpuFeatures.c
src/includes/perfmon_skylake.h
src/perfmon.c
src/power.c
src/topology.c

Intel Comet Lake in-core support is comparable with Intel Skylake/Kabylake or Cannonlake. It also uses the same event lists.
See issue #359 .

Add support for Intel Comet Lake

---

test/check_data_files.py

Ignore comments at the end of lines in event description files.

check_data_files.py: ignore comments when parsing events

---

src/applications/likwid-perfscope.lua

Hi, @TomTheBear 
I found there is an issue when likwid-perfscope drawing multi-core events curves
```bash
likwid-perfscope -t 1s -g L3 -c 0,4 likwid-bench -s 5s -t stream_avx -w S0:1MB:2
```
1. Only one curve align to y2
2. Core events are not align to the right core legends
I fixed this issue with the PR

Fix perfscope when drawing y2title with multi-core

---

groups/arm64fx/FP_PIPE.txt

This group is inspired by metrics gathered by the Fujitsu Advanced Profiler `fapp`. The group measures how well the FP ports are utilized.

Adding group for FP pipeline rates for Fujitsu A64FX

---

bench/armv8/sum_sve128.ptt
bench/armv8/sum_sve256.ptt
bench/armv8/sum_sve512.ptt

This PR adds the three kernels `sum_sve128`, `sum_sve256` and `sum_sve512` for ARM SVE

Vector sum benchmarks with SVE

---

src/affinity.c
src/includes/topology.h
src/numa_proc.c
src/topology.c
src/topology_hwloc.c
src/topology_proc.c

This PR fixes topology issues on the Fugaku nodes. I'm not sure what the difference between the FX1000 I used before is.
One problem is the naming of affinity domains. The first 4 packages and NUMA domains do not contain any usable hardware thread (just management cores). If we name the affinity domains as normal, they would be called `S4`-`S7` (and `M4`-`M7`). This PR uses zero-based numbering, so although the socket has e.g. the ID 4, the affinity domain is called `S0`.

Fugaku topology fix

---

packaging/rpm/likwid.spec

This commit, add the perl-Data-Dumper package as rpm build requirement.
Otherwise an rpmbuild with the provided specfile will fail.

Add missing build requirement for rpm specfile

---

src/includes/perfmon_perfevent.h

In most cases it is not required to do multiplexing because LIKWID never uses more events than there are physical counter registers for CPUs. The Intel Skylake SP architecture (and maybe Cascadelake SP) has a bug in the `PMC3` if transactional memory is enabled (see #224 or [likwid-users mailing list post](https://groups.google.com/g/likwid-users/c/VlllTO0qv-c)). This causes that perf_event multiplexes on the remaining 3 counters and LIKWID has to evaluate the multiplexing information to calculate the real counter value.

Fix for perf_event multiplexing

---

filters/json
filters/xml
src/applications/likwid-perfctr.lua

- Fixes parsing of `likwid-topology` and `likwid-perfctr`
- Simplifies filter code
- Enable output file with timeline mode
- CLI Option (not in help output yet) to add output prefix to timeline mode lines. This is required to implement timeline mode for `likwid-mpirun`

Fix likwid-perfctr filter and enable timeline mode to output file

---

src/access_client.c
src/access_x86_msr.c
src/access_x86_rdpmc.c
src/includes/access_x86_rdpmc.h

This PR adds a new access layer to the current access system. It can be used to bypass costly direct MSR or PCI reads or the accessdaemon when accessing the `PMC` and `FIXC` counters on Intel and AMD.

Bypass daemon

---

src/numa.c
src/topology.c

New environment variable `LIKWID_IGNORE_CPUSET`. The variable affects all tools and the library. Maybe fixes #358, not tested `isolcpus` explicitly. 
```
System with 8 hardware threads (SMT active)
$ taskset -c -p $$
pid's current affinity list: 0-2
$ likwid-pin -c 0,1 -p
INFO: You are running LIKWID in a cpuset with 3 CPUs. Taking given IDs as logical ID in cpuset
0,1
$ likwid-pin -c 3,4 -p
INFO: You are running LIKWID in a cpuset with 3 CPUs. Taking given IDs as logical ID in cpuset
0,1
$ LIKWID_IGNORE_CPUSET=1 ./likwid-pin -c 3,4 -p
3,4
```
It does not ignore the CPUset but creates an own CPUset containing `X` **online** CPUs where `X=sysconf(_SC_NPROCESSORS_CONF)`. This should be fine for almost all use-cases.

New environment variable `LIKWID_IGNORE_CPUSET` to ignore the current cpuset

---

groups/arm64fx/MEM.txt
groups/arm64fx/MEM_DP.txt
groups/arm64fx/MEM_HP.txt
groups/arm64fx/MEM_SP.txt

Metrics and correction terms taken from the fujitsu a64fx microarchitectural manual v1.4 page 85 and the a64fx pmu events errata v1.0.
```
L2D_CACHE_REFILL (corrected) = L2D_CACHE_REFILL - L2D_SWAP_DM - L2D_CACHE_MIBMCH_PRF
Bandwidth (corrected) = (L2D_CACHE_REFILL - (L2D_SWAP_DM + L2D_CACHE_MIBMCH_PRF) + L2D_CACHE_WB) * 256 / time
```
- https://github.com/fujitsu/A64FX/blob/master/doc/A64FX_Microarchitecture_Manual_en_1.4.pdf
- https://github.com/fujitsu/A64FX/blob/master/doc/A64FX_PMU_Events_Errata_1.0.pdf

Update arm64fx MEM groups bandwidth metrics

---

src/perfmon.c
src/topology.c

This PR adds all ARM-reference implementation (A35, A53, A72, A73, Neoverse N1) for 32bit (aka ARMv7 in some cases) and 64bit (ARMv8) to the topology module.

Some fixes for ARM7 and ARM8

---

src/applications/likwid-setFrequencies.lua

When setting the governor with `likwid-setFrequencies`, the minimal and maximal CPU frequency of all selected HW threads is set to the minimal frequency. This PR fixes this behavior by leaving the CPU frequency untouched.

Fix for min. frequency after setting governor. See #404

---

bench/armv8/peakflops.ptt
bench/armv8/peakflops_fma.ptt
bench/armv8/peakflops_sp.ptt
bench/armv8/peakflops_sp_fma.ptt
bench/armv8/peakflops_sp_sve128.ptt
bench/armv8/peakflops_sp_sve128_fma.ptt
bench/armv8/peakflops_sp_sve256.ptt
bench/armv8/peakflops_sp_sve256_fma.ptt
bench/armv8/peakflops_sp_sve512.ptt
bench/armv8/peakflops_sp_sve512_fma.ptt
bench/armv8/peakflops_sve128.ptt
bench/armv8/peakflops_sve128_fma.ptt
bench/armv8/peakflops_sve256.ptt
bench/armv8/peakflops_sve256_fma.ptt
bench/armv8/peakflops_sve512.ptt
bench/armv8/peakflops_sve512_fma.ptt

Created peakflops benchmarks for likwid-bench on ARMv8. This includes
- Benchmarks for SP and DP operands
- A combination of MUL and ADD, or pure FMA instructions
- Scalar, SVE128, SVE256, and SVE512 versions
When running those on a single core as `likwid-bench -t BENCHMARK -w S0:40kB:1` and comparing the result with the expected peak performance, all benchmarks reach more than 99% of the theoretical peak performance:
```
benchmark               measured_MFLOPS expected_MFLOPS relative_performance_%
peakflops               3587.83         3600.0          99.66
peakflops_fma           7174.63         7200.0          99.65
peakflops_sve128        7170.39         7200.0          99.59
peakflops_sve128_fma    14340.99        14400.0         99.59
peakflops_sve256        14315.83 …
```

Peakflops armv8

---

src/libperfctr.c

Fix a bug due to the unreleased lock before the method likwid_markerStopRegion returns. Insert the unlock statement before returning.

Fix a bug due to the unrelased lock before the method returns (the issue#416)

---

src/includes/nvmon_perfworks.h

Nvidia changed the way how to determine the subevents required for a metric. Fixes #423

Fix Cuda builds for version >= 11.4

---

src/applications/likwid-perfctr.lua
src/includes/nvmon_perfworks.h
src/includes/nvmon_types.h
src/libnvctr.c
src/topology_gpu.c

This PR contains different updates:
- Ability for the perfworks backend to use min,max,sum and spot values
- Don't use `fprintf` in the code but the debug/error macros provided by LIKWID
- `likwid-perfctr`: Initialize the Nvidia GPU modules only if needed (user wants to measure, print or search events). See #427

Update Nvidia GPU support

---

src/includes/perfmon_a57_counters.h
src/perfmon.c

If `/sys/bus/event_source/devices/armv8_pmuv3` does not exist, use `/sys/bus/event_source/devices/armv8_cortex_a72`.

Check perf device path for ARM8 A72 with fallback. Fixes #425

---

src/perfmon.c
src/topology.c
src/topology_hwloc.c

Potential fix for the issue as described in #483.

Potential fix for likwid-perfctr not working on Cortex A53 when running in ARMv7 mode

---

bench/armv8/peakflops_neon.ptt
bench/armv8/peakflops_neon_fma.ptt
bench/armv8/peakflops_sp_neon.ptt
bench/armv8/peakflops_sp_neon_fma.ptt

Added benchmark `peakflops_neon_fma` for peakflops with NEON SIMD extension

added new peakflops likwid-bench benchmark for NEON

---

src/topology_hwloc.c

In a previous commit, the path to the `cpuinfo` file was changed to just `"cpuinfo"` instead of `"/proc/cpuinfo"`. This causes ARM processors to not be recognized.
This commit simply changes that path back to `/proc/cpuinfo`.

Fix cpuinfo path used in topology_hwloc.c on ARM devices

---

src/access_x86_rdpmc.c

Checking for RDPMC support is done in a `fork()`'ed child process, and when the parent is a Julia process there can be exit handlers registered that will crash in the child process. We can get around that by using `_exit()` instead, which doesn't run exit handlers.
Fixes https://github.com/JuliaPerf/LIKWID.jl/issues/51 for me. AFAIK it's safe to use `_exit()` here, according to the [docs](https://man7.org/linux/man-pages/man2/_exit.2.html) the only things to be wary of are stdio streams not being flushed (but we don't print anything in the child) and open file descriptors being closed (I can't see any file descriptors used in the child). I can't see any difference in signal handling either.
CC @carstenbauer

Use _exit() instead of exit() when checking for RDPMC support

---

src/access_x86_rdpmc.c

Inspired by https://github.com/RRZE-HPC/likwid/pull/519#issuecomment-1460605455.

Use quick_exit() instead of _exit()

---

make/config_checks.mk

Copy likwid.mod from BASE_DIR, shell internally might be in a different folder
Fixes #561

Fix Fortran interface installation

---

src/applications/likwid-features.lua

A development version of `likwid-sysfeatures` slipped into with the SPR merge. This PR reverts `likwid-features` back to the original one.

Revert to old `likwid-features` CLI application

---

filters/json

The script currently crashes when a result is `-` (not counted or device does not exist). This fix replaces these values with `NaN` for JSON. Although `NaN` is not officially allowed by the JSON standard, the Python JSON module handles them properly: http://docs.python.org/library/json.html#basic-usage

Fix for JSON filter script

---

Makefile
make/config_defines.mk
src/access-daemon/Makefile
src/access-daemon/appDaemon.c
src/applications/likwid-perfctr.lua
src/applications/likwid.lua
src/includes/likwid-marker.h
src/includes/likwid.h
src/libnvctr.c
src/likwid.F90
src/likwid_f90_interface.c
src/luawid.c
src/rocmon_marker.c

Add write result file function for Nvidia GPU and AMD GPU.

---

groups/SPR/L2CACHE.txt
groups/SPR/L3CACHE.txt

Hi @TomTheBear,
This PR adds the two performance groups `L2CACHE` and `L3CACHE` to the Intel SapphireRapids architecture. These groups also exist for previous architectures and were adapted from the existing group files. The following adoptions were made:
- In SapphireRapids, the `L2_TRANS_ALL_REQUESTS` event of the `L2CACHE` group no longer exists and was replaced by the `L2_REQUEST_ALL` event. For consistency within the group file `L2_RQSTS_MISS` was replaced by its alias `L2_REQUEST_MISS`.
- As [this comment](https://github.com/RRZE-HPC/likwid/blob/master/groups/ICL/L3CACHE.txt#L35-L36) ("With Intel Icelake, the retired UOPs cannot be measured anymore but instead, [...]") indicates, SapphireRapids no longer supports the counting of all retired UOPs. Therefore, the `L3CACHE` group uses …

Add Performance Groups for Caches to Intel SapphireRapids

---

src/likwid_f90_interface.c

The undefined variable causes build errors when setting `FORTRAN_INTERFACE=true` and `NVIDIA_INTERFACE=true`.

Fix undefined variable in f90 interface

---

.gitignore
Makefile
config.mk
make/config_defines.mk
src/access_client.c
src/bridge/bridge.c

Hi,
Most HPC systems grant only a basic set of permissions (i.e. no sudo, no CAP_SYS_ADMIN). This means that only non-sudo container technologies are ready available to the end users. 
Using likwid in unprivileged containers like Apptainer can be problematic. The `perf_event` method does work provided that the `per_event_paranoid` setting is low enough, but the data is often limited (the clusters I've tested had all `perf_event_paranoid=2`). Setuid binaries don't get any additional privileges when executed inside an unprivileged container, so spawning access daemons inside the container isn't an option either.
This PR demonstrates how we can utilise the power of the access daemon installed on the host machine inside Apptainer. The general idea is to have a process on the host that listens …

likwid-bridge: a helper tool to run likwid in containers like Apptainer

---

src/affinity.c
src/topology_proc.c

bug 1: numCachesPerSocket is 0 and numberOfDomains is therefore calculated incorrectly resulting in writes to not allocated mem
bug 2: 24-core version of a64fx is essentiually a 48 core with some cores being disabled, but the core IDs are not numbered consecutively by the kernel resulting in segfaults in likwid

fixing two bugs which result in crashes on a 24-core a64fx (related to issue #599)

---

src/access_x86_msr.c
src/access_x86_pci.c
src/configuration.c
src/includes/frequency.h
src/includes/lock.h
src/includes/types.h

and in the process i cleaned up init_configuration a bit

allow user-supplied cfg and topo files via env var

---

src/includes/perfmon_neon1_counters.h
src/includes/topology.h
src/perfmon.c
src/topology.c

Since I am currently trying to use Likwid on a Raspberry Pi 5 which features an ARM Cortex A76 that is not supported yet, I added the topology definitions to `topology.h` and `topology.c` and also the counter + event definitions. Since they look to be identical, I reused the Neon 1 counter and event setup like was done for the Cortex A72 which uses the Cortex A57 definitions.

Add support for ARM Cortex A76 reusing Neon N1 counters and events

---

src/includes/likwid.h
src/includes/sysFeatures_common.h
src/includes/sysFeatures_nvml.h
src/likwid_device.c
src/nvmon.c
src/sysFeatures.c
src/sysFeatures_common.c
src/sysFeatures_linux_numa_balancing.c
src/sysFeatures_nvml.c

This PR adds sysfeature support for Nvidia NVML. In addition, a few fixes are provided to enable the creation of LikwidDevices of type `nvidia_gpu`.

Add sysFeatures_nvml module

---

src/power.c
src/sysFeatures_intel_rapl.c

Hi @TomTheBear,
this PR directly addresses the issue reported in #642. Although the implemented changes are really minor, I tested it on our system and the reported numbers are indeed ~4 times higher (new 61 uJ / old 15,3 uJ = 3,9869281).
Greetings
Christian

Fix RAPL DRAM energy unit for Sapphire Rapids (SPR)

---

src/applications/likwid-sysfeatures.lua
src/includes/amd_hsmp.h
src/includes/sysFeatures_amd_hsmp.h
src/includes/sysFeatures_common_rapl.h
src/includes/sysFeatures_types.h
src/luawid.c
src/sysFeatures_amd.c
src/sysFeatures_amd_hsmp.c
src/sysFeatures_common.c

The support currently requires the kernel module `amd_hsmp` to be manually loaded and appropriate read/write permissions. Read only/Write only is not supported.

Add AMD HSMP support to sysfeatures

---

groups/ICX/L3CACHE.txt

Hi everyone,
just as the title reads, this PR adds the existing L3CACHE group from ICL to ICX as well. The events work the same on both architectures (see [ICL here](https://github.com/intel/perfmon/blob/dbd3a0054701814c0f833df641410d0647b05184/ICL/events/icelake_core.json) and [ICX here](https://github.com/intel/perfmon/blob/dbd3a0054701814c0f833df641410d0647b05184/ICX/events/icelakex_core.json)); just seems like a minor oversight when these groups were initially added.
Thanks for integrating this change. Greetings
Christian

Add Icelake L3CACHE group to IcelakeX

---

src/includes/perfmon_types.h
src/includes/registers_types.h
src/perfmon.c

In 638191a211e71d4d0db42eebe839a0ff187354e0 the enum `RegisterType` has been extended. This results in overflows for HBM events: `Cannot set out-of-bounds event->type 489` up to 510 in this case.
**Before:**
```
+-------------------------------------+------------+-----------+-----------+-----------+-----------+-----------+-----------+
|                Metric               |     Sum    |    Min    |    Max    |    Avg    |  %ile 25  |  %ile 50  |  %ile 75  |
+-------------------------------------+------------+-----------+-----------+-----------+-----------+-----------+-----------+
|       Runtime (RDTSC) [s] STAT      |   299.9565 |   12.4427 |   12.5986 |   12.4982 |   12.4612 |   12.4832 |   12.5143 |
|      Runtime unhalted [s] STAT      |   350.0533 |   13.6187 |   15.0294 |   14.5856 …
```

Fixes HBM Metric

---

make/include_ICX.mk

Here's a naive makefile for the new clang-based Intel "oneAPI" compilers. It's copied from `include_ICC.mk`, I only changed the compiler names.
To make this work with spack, at least the following edit to likwid's `package.py` is needed:
```diff
diff --git a/var/spack/repos/builtin/packages/likwid/package.py b/var/spack/repos/builtin/packages/likwid/package.py
index c3f297445f..2782c8b8ab 100644
--- a/var/spack/repos/builtin/packages/likwid/package.py
+++ b/var/spack/repos/builtin/packages/likwid/package.py
@@ -159,6 +159,7 @@ def install(self, spec, prefix):
"clang": "CLANG",
"gcc": "GCC",
"intel": "ICC",
+            "oneapi": "ICX",
}
if spec.target.family == "aarch64":
supported_compilers = {"gcc": "GCCARMv8", "clang": "ARMCLANG", "arm": "ARMCLANG"}
```
feel free to edit!

make: add makefile for oneapi/ICX

---

Makefile
bench/Makefile
config.mk
ext/hwloc/Makefile
make/include_CLANGARMv8.mk
src/access-daemon/Makefile

This is an attempt to make likwid compile on ARM with llvm clang. Right now I am testing on a Neoverse-N1 with llvm@19.1.7.
I added the config file for CLANGARMv8 merging the ones for ARMCLANG, CLANG and GCCARMv8.

Adding support for llvm clang on arm

---

src/rocmon.c
src/topology_rocm.c

This PR proposes fixes for bugs in the ROCm performace monitoring and topology module of LIKWID.
- Changed the method for obtaining HIP function pointers by using the hipGetProcAddress function to prevent incorrect identifier substitution in the HIP library
- Fixes the freeing of events in the event result lists by using the event index instead of the device index
- Adds the reset of the initialization flag to the finalization processes to prevent invalid memory accesses when calling the finalization function multiple times
- Removes excess quotation marks in ERROR_PRINT

Fixes some bugs in the ROCm modules

---

src/includes/likwid.h

Fixes #686 by adding the missing `__attribute__((visibility("default")))` annotations.

Add missing default visibility for nvmon_getEventsOfGpu and nvmon_returnEventsOfGpu in likwid.h
